### ISSUE TITLE
Almost all codeblocks are broken

### ISSUE THREAD

**Issue by theS1LV3R** [freeipa/freeipa.github.io#25]
After migrating to a new theme (it looks like) a while ago, most code blocks have been broken.

All the broken examples are from the page on [Certmonger](https://www.freeipa.org/page/Certmonger#manually-renew-a-certificate), however more pages are broken as well.

Examples of how it looks:
![image](https://github.com/freeipa/freeipa.github.io/assets/32072697/599364d9-d264-4f27-9a25-41ddc8864855)
![image](https://github.com/freeipa/freeipa.github.io/assets/32072697/74671abe-f8a5-432f-bc75-b535baa8fa1b)
![image](https://github.com/freeipa/freeipa.github.io/assets/32072697/83228880-db8f-4e77-96d2-3b3670c7dd76)

Example of how its supposed to look:
![image](https://github.com/freeipa/freeipa.github.io/assets/32072697/56236e71-df4d-40c7-9d2f-38161630d7e8)

**Comment by jeffclay** [comment]
@theS1LV3R do you know which PR broke everything? I came here myself to fix the code blocks for [Polkit](https://www.freeipa.org/page/Howto/FreeIPA_PolicyKit). Maybe there's a fix that can be applied to all the pages and they won't have to be patched individually.

**Comment by theS1LV3R** [comment]
It seems like https://github.com/freeipa/freeipa.github.io/commit/bc322df30e213543c7153eac96d6ecb3005d8da9 introduced the files, with the broken syntax. I am guessing the errors are either:
- coming from a broken transformation in the commit; or
- that the software that turns `.rst` into `.html` isn't compatible with the syntax

Either way, I have no clue here to start debugging/fixing

**Comment by jeffclay** [comment]
@theS1LV3R Can you take a look at the staging preview from my PR [https://www.freeipa.org/pull/35/page/Certmonger](https://www.freeipa.org/pull/35/page/Certmonger) and let me know if that's about how it's supposed to look?

**Comment by jeffclay** [comment]
@theS1LV3R FYI I cancelled the PR. I was still coming across random stuff that wasn't updated. Going to do a more thorough review.

**Comment by theS1LV3R** [comment]
Fixed by #37
