### ISSUE TITLE
Improve HBAC configuration for AIX

### ISSUE THREAD

**Issue by rseabra** [freeipa/freeipa.github.io#48]
Hi,

Some years ago I wrote a PAM module to add HBAC support for the AIX servers at the company I work at, but deployment has been slow.

We're finally going through a roll out, and I noticed that https://www.freeipa.org/page/ConfiguringAixClients has a bad HBAC model proposal, and allows locked in users to log in (for instance if they use ssh public keys).

So I created PR #47 with some improvements.

I also have a couple of things to add regarding SSH, but I'd rather do that work in a different branch and PR.

Br,
Rui

**Comment by abbra** [comment]
merged #47
